package org.cls;

public class Col_Unchk_Excep_Handling {
	
	public static void main(String[] args) {
	
	//printStackTrace Method to display exception msg details
		
		System.out.println(0);
		System.out.println(1);
		try {
			System.out.println(2/0);
		} 
		catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}
		
		System.out.println(3);
		System.out.println(4);
				
	
//		System.out.println(0);
//		System.out.println(1);
//		System.out.println(2);
//		// to handle the exception
//		// one is not exception nd other one is exception
//		try {
//			System.out.println(3);
//			String s = null;
//			System.out.println(s.charAt(0));
//		} 
////		catch (NullPointerException e) {
////			System.out.println("Handled1");
////		}
//		catch (ArithmeticException e) {
//			System.out.println("Handled2");
//		}
//		catch (ArrayIndexOutOfBoundsException e) {
//			System.out.println("Handled3");
//		}
//		finally {
//			System.out.println("finally..");
//		}
//		System.out.println(4);
//		System.out.println(5);
//		
		

		
//		System.out.println(0);
//		System.out.println(1);
//		System.out.println(2);
//		// to handle the exception
//		
//		// if given more exceptions but one 1 will b executed
//		try {
//			System.out.println(3/0);
//			String s= null;
//			System.out.println(s.charAt(0));
//		} 
//		catch (NullPointerException e) {
//			System.out.println("Handled1");
//		}
//		catch (ArithmeticException e) {
//			System.out.println("Handled2");
//		}
//		catch (ArrayIndexOutOfBoundsException e) {
//			System.out.println("Handled3");
//		}
//		finally {
//			System.out.println("finally..");
//		}
//		System.out.println(4);
//		System.out.println(5);
//		
		

		
//		System.out.println(0);
//		System.out.println(1);
//		System.out.println(2);
//		// to handle the exception
//		try {
//			System.out.println(3/0);
//		} 
//		catch (NullPointerException e) {
//			System.out.println("Handled1");
//		}
//		catch (ArithmeticException e) {
//			//System.out.println("Handled2");
//		}
//		catch (ArrayIndexOutOfBoundsException e) {
//			System.out.println("Handled3");
//		}
//		
//		System.out.println(4);
//		System.out.println(5);
//		
		
	
	
		
//		System.out.println(0);
//		System.out.println(1);
//		System.out.println(2);
//		// to handle the exception
//		try {
//			System.out.println(3/0);
//		} 
//		catch (NullPointerException e) {
//			System.out.println("Handled1");
//		}
//		catch (ArithmeticException e) {
//			System.out.println("Handled2");
//		}
//		catch (ArrayIndexOutOfBoundsException e) {
//			System.out.println("Handled3");
//		}
//		
//		System.out.println(4);
//		System.out.println(5);
//		
		
		
//		System.out.println(0);
//		System.out.println(1);
//		System.out.println(2);
//		// to handle the exception
//		try {
//			System.out.println(3/0);
//		} 
//		catch (NullPointerException e) {
//			System.out.println("Handled1");
//		}
//		catch (ArithmeticException e) {
//			System.out.println("Handled2");
//		}
//		catch (ArrayIndexOutOfBoundsException e) {
//			System.out.println("Handled3");
//		}
//		finally {
//			System.out.println("Finally..");
//		}
//		System.out.println(4);
//		System.out.println(5);
		
//		System.out.println(0);
//		System.out.println(1);
//		System.out.println(2);
//		// to handle the exception
//		try {
//			System.out.println(3/0);
//		} 
//		catch (NullPointerException e) {
//			System.out.println("Handled1");
//		}
//		catch (NumberFormatException e) {
//			System.out.println("Handled2");
//		}
//		catch (ArrayIndexOutOfBoundsException e) {
//			System.out.println("Handled3");
//		}
//		finally {
//			System.out.println("Finally..");
//		}
//		System.out.println(4);
//		System.out.println(5);
		
	
		
		
		
//		
//		// Arithemetic Execption
//		
//		System.out.println(0);
//		System.out.println(1);
//		System.out.println(2);
//		
//		//System.out.println(3/0); //-- exception
//		// to handle the exception
//		try {
//			System.out.println(3/0);
//		} 
//		//catch (Exception e) { // insted of exception u can give Arithemetic exception 
//			
//		//catch (ArithmeticException e) {
//		// if the given exception in catch is not match to the occured
//		catch (NullPointerException e) {
//		// TODO: handle exception
//			System.out.println("Handled");
//		}
//		
//		System.out.println(4);
//		System.out.println(5);
//		
//	
	}

}
